#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import subprocess
import time


ROOT = Path(__file__).resolve().parents[1]

SIGNALS = [
    "TOP.clk",
    "TOP.rst_n",
    "TOP.in_data[7:0]",
    "TOP.in_valid",
    "TOP.in_ready",
    "TOP.in_sop",
    "TOP.in_eop",
    "TOP.meta_valid",
    "TOP.meta_ready",
    "TOP.state_dbg[2:0]",
    "TOP.byte_idx_dbg[15:0]",
    "TOP.eth_frame_parser.accept",
]


def write_savefile(case: str, vcd: Path, savefile: Path) -> None:
    savefile.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "[*]",
        "[*] GTKWave save file generated by tools/capture_gtkwave_screenshot.py",
        "[*]",
        f'[dumpfile] "{vcd}"',
        f'[savefile] "{savefile}"',
        "[timestart] 0",
        "[size] 1400 850",
        "[pos] 80 80",
        "*-1.000000 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0",
        "[sst_width] 260",
        "[signals_width] 250",
        "[sst_expanded] 1",
        "[sst_vpaned_height] 170",
        "@28",
        f"-{case}",
        "@28",
    ]
    lines.extend(SIGNALS)
    lines.extend(["[pattern_trace] 1", "[pattern_trace] 0", ""])
    savefile.write_text("\n".join(lines), encoding="utf-8")


def activate_gtkwave(pid: int) -> None:
    script = f'''
tell application "System Events"
  set waveProc to first process whose unix id is {pid}
  set frontmost of waveProc to true
  delay 0.4
  try
    set position of window 1 of waveProc to {{60, 60}}
    set size of window 1 of waveProc to {{1400, 850}}
  end try
end tell
'''
    subprocess.run(["osascript", "-e", script], check=False)


def main() -> int:
    parser = argparse.ArgumentParser(description="Capture a waveform screenshot from GTKWave")
    parser.add_argument("--case", default="valid_ipv4_udp_min_payload")
    parser.add_argument("--vcd", help="VCD file to load. Defaults to waves/<case>.vcd")
    parser.add_argument("--savefile", help="GTKWave savefile path. Defaults to waves/<case>.gtkw")
    parser.add_argument("--out", help="PNG path. Defaults to screenshots/<case>_gtkwave.png")
    parser.add_argument("--wait-sec", type=float, default=3.0)
    parser.add_argument("--gtkwave", default="gtkwave")
    args = parser.parse_args()

    vcd = Path(args.vcd) if args.vcd else ROOT / "waves" / f"{args.case}.vcd"
    if not vcd.is_absolute():
        vcd = ROOT / vcd
    if not vcd.exists():
        raise SystemExit(f"VCD not found: {vcd}. Run `make waves CASE={args.case}` first.")

    savefile = Path(args.savefile) if args.savefile else ROOT / "waves" / f"{args.case}.gtkw"
    if not savefile.is_absolute():
        savefile = ROOT / savefile
    out = Path(args.out) if args.out else ROOT / "screenshots" / f"{args.case}_gtkwave.png"
    if not out.is_absolute():
        out = ROOT / out
    out.parent.mkdir(parents=True, exist_ok=True)

    write_savefile(args.case, vcd, savefile)

    proc = subprocess.Popen([args.gtkwave, str(vcd), str(savefile)], cwd=ROOT)
    try:
        time.sleep(args.wait_sec)
        activate_gtkwave(proc.pid)
        time.sleep(0.8)
        subprocess.run(["screencapture", "-x", str(out)], check=True)
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()

    if not out.exists() or out.stat().st_size == 0:
        raise SystemExit(f"GTKWave screenshot was not created: {out}")

    print(f"Wrote {out}")
    print(f"Wrote {savefile}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
